<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            // [
            //     'kode_buku' => '101',
            //     'judul' => 'Belajar Coding',
            //     'pengarang' => 'Nicholas Doloksaribu',
            //     'penerbit' => 'Informatika Bandung',
            //     'tahun_terbit' => '2023',
            //     'call_number' => '005.1 NIC p',
            //     'deskripsi' => 'Buku ini membahas Laravel dari dasar hingga mahir.',
            //     'isbn' => '9786021234567',
            //     'foto_buku' => 'laravel.jpg',
            //     'stok' => 5,
            //     'rak' => 'A1',
            //     'kategori' => 'Teknologi',
            // ],
            // [
            //     'kode_buku' => '102',
            //     'judul' => 'Dasar-dasar Matematika Terapan',
            //     'pengarang' => 'Budi Santoso',
            //     'penerbit' => 'Graha Ilmu',
            //     'tahun_terbit' => '2022',
            //     'call_number' => '510 BUD d',
            //     'deskripsi' => 'Penjelasan lengkap konsep matematika diskrit.',
            //     'isbn' => '9786022345678',
            //     'foto_buku' => 'matdis.jpg',
            //     'stok' => 3,
            //     'rak' => 'B2',
            //     'kategori' => 'Matematika',
            // ],
            // [
            //     'kode_buku' => '103',
            //     'judul' => 'Pengantar Blockchain',
            //     'pengarang' => 'Sari Lestari',
            //     'penerbit' => 'DeepPublish',
            //     'tahun_terbit' => '2024',
            //     'call_number' => '006 SAR p',
            //     'deskripsi' => 'Memahami konsep dasar Artificial Intelligence.',
            //     'isbn' => '9786023456789',
            //     'foto_buku' => 'ai.jpg',
            //     'stok' => 4,
            //     'rak' => 'C3',
            //     'kategori' => 'Teknologi',
            // ],
            [
                'kode_buku' => '104',
                'judul' => 'Matematika Diskrit Lanjutan',
                'pengarang' => 'Alfredo Pangestu',
                'penerbit' => 'Graha Ilmu',
                'tahun_terbit' => '2023',
                'call_number' => '510 PAN m',
                'deskripsi' => 'Pembahasan lebih dalam tentang teori graf dan logika matematika.',
                'isbn' => '9786023456780',
                'foto_buku' => 'matdiskritlanjutan.jpg',
                'stok' => 2,
                'rak' => 'B2',
                'kategori' => 'Matematika',
            ],
            [
                'kode_buku' => '105',
                'judul' => 'Dasar-dasar Kecerdasan Buatan',
                'pengarang' => 'Yulia Manurung',
                'penerbit' => 'DeepPublish',
                'tahun_terbit' => '2024',
                'call_number' => '006.3 MAN d',
                'deskripsi' => 'Pengenalan dan konsep dasar dalam kecerdasan buatan.',
                'isbn' => '9786023456790',
                'foto_buku' => 'aiintro.jpg',
                'stok' => 3,
                'rak' => 'C4',
                'kategori' => 'Teknologi',
            ],
            [
                'kode_buku' => '106',
                'judul' => 'Pemrograman Python untuk Pemula',
                'pengarang' => 'Dian Sastrowardoyo',
                'penerbit' => 'Informatika Bandung',
                'tahun_terbit' => '2022',
                'call_number' => '005.1 SAS p',
                'deskripsi' => 'Buku ini membahas pemrograman Python dengan contoh praktis.',
                'isbn' => '9786021234578',
                'foto_buku' => 'python.jpg',
                'stok' => 4,
                'rak' => 'A1',
                'kategori' => 'Teknologi',
            ],
            [
                'kode_buku' => '107',
                'judul' => 'Matematika Terapan dalam Kehidupan Sehari-hari',
                'pengarang' => 'Rizky Pratama',
                'penerbit' => 'Informatika Bandung',
                'tahun_terbit' => '2021',
                'call_number' => '510 PRI m',
                'deskripsi' => 'Buku yang menjelaskan penerapan matematika dalam kehidupan sehari-hari.',
                'isbn' => '9786029876543',
                'foto_buku' => 'mataplikasi.jpg',
                'stok' => 6,
                'rak' => 'B2',
                'kategori' => 'Matematika',
            ],
            [
                'kode_buku' => '108',
                'judul' => 'Algoritma dan Struktur Data',
                'pengarang' => 'Mulyanto',
                'penerbit' => 'Informatika Jakarta',
                'tahun_terbit' => '2020',
                'call_number' => '005.3 MUL a',
                'deskripsi' => 'Buku ini membahas konsep dasar algoritma dan struktur data dalam pemrograman.',
                'isbn' => '9786028765432',
                'foto_buku' => 'algoritma.jpg',
                'stok' => 5,
                'rak' => 'A3',
                'kategori' => 'Teknologi',
            ],
            [
                'kode_buku' => '109',
                'judul' => 'Dasar-Dasar Pengolahan Citra Digital',
                'pengarang' => 'Fauzi Hidayat',
                'penerbit' => 'Graha Ilmu',
                'tahun_terbit' => '2022',
                'call_number' => '006.4 HID d',
                'deskripsi' => 'Buku ini mengulas tentang dasar pengolahan citra menggunakan perangkat lunak.',
                'isbn' => '9786023345678',
                'foto_buku' => 'citralatihan.jpg',
                'stok' => 3,
                'rak' => 'C5',
                'kategori' => 'Teknologi',
            ],
            [
                'kode_buku' => '110',
                'judul' => 'Teori Graf dan Aplikasinya',
                'pengarang' => 'Budi Santoso',
                'penerbit' => 'Graha Ilmu',
                'tahun_terbit' => '2023',
                'call_number' => '510 SAN t',
                'deskripsi' => 'Buku ini menjelaskan teori graf dan penerapannya dalam berbagai bidang.',
                'isbn' => '9786027654321',
                'foto_buku' => 'teorigraf.jpg',
                'stok' => 5,
                'rak' => 'B3',
                'kategori' => 'Matematika',
            ]
        ]);
    }
}
